integer=327;
print(integer);
stringa="stroka";
print(stringa);
plavaet=3.27;
print(plavaet);
isBool = True;
print(isBool);
integer=int(input("Введите число:"));
print(integer);
print(type(integer));
stringa=input("Введите строку:");
print(stringa);
print(type(stringa));
plavaet=float(input("Введите дробь:"));
print(plavaet);
print(type(plavaet));
isBool=bool(input("True of False"));
print(isBool);
print(type(isBool));
